### PR TITLE
Update to Ember 2.3 and fix deprecations

### LINKED ISSUE #49: Update to Ember 2.3.0.
- [ ] Fix deprecations
- [ ] Upgrade :smiling_imp:

### PR DESCRIPTION
**Pull request by raido**
Upgrade to Ember 2.3

Fix initial deprecations. I'll look around and see if more comes up.

Closes #49

### CODE REVIEW

**Comment by acorncom** [comment]
LGTM!  @rwjblue I've checked this over, things seem to be running smoothly, would you merge when you get a chance?

**Comment by rwjblue** [comment]
Dang, looks like a recent merge causes a merge conflict. Can you rebase?

**Comment by rwjblue** [comment]
@raido - I'd love to pull this in, would you mind rebasing?

**Comment by raido** [comment]
@rwjblue - Rebased.

**Comment by rwjblue** [comment]
Thank you!

**Pull request merged**
