### PR TITLE
Update ember-cli + related deps, & re-init

### PR DESCRIPTION
**Pull request by davewasmer**
Should be pretty straight forward. Just `npm i -D ember-cli@*` and `ember init`.

**Edit**
Also removed ember-data, since it's not really in use.

### CODE REVIEW

**Comment by locks** [comment]
> Should be pretty straight forward

Famous last words :trollface:

**Comment by davewasmer** [comment]
It's basically become a positive affirmation for me - if I say it enough, maybe it will be true one day? 😜

**Comment by rwjblue** [comment]
Thank you!

**Comment by acorncom** [comment]
@davewasmer :stuck_out_tongue_winking_eye:

**Pull request merged**
